services:
  traefik:
    image: traefik:v3.3.3
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic:/etc/traefik/dynamic
      # Update this path to match exactly what Traefik is looking for
      - ../:/plugins-local/src/github.com/sistemica/traefik-path-param-headers
    networks:
      - traefik-net

  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - traefik-net

networks:
  traefik-net:
    name: traefik-net