## Dynamic configuration 

http:
  middlewares:
    path-params:
      plugin:
        pathparamheaders:
          pathPattern: "/products/{category}/{id}"
          headerPrefix: "X-Path-"
  
  # Define our backend service directly
  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000"
  
  # Define our router
  routers:
    test-router:
      rule: "Host(`test.localhost`) && PathRegexp(`^\\/products\\/([^\\/]+)\\/([^\\/]+)$`)"
      service: "backend"
      middlewares:
        - "path-params"