## Static configuration for Traefik v3
log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

# Enable experimental features (needed for plugins)
experimental:
  localPlugins:
    pathparamheaders:
      moduleName: github.com/sistemica/traefik-path-param-headers